// <auto-generated />
using System;
using Flit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flit.Infrastructure.Migrations
{
    [DbContext(typeof(FlitDbContext))]
    [Migration("20260603213655_AddProceduresConfigRulesRgl01")]
    partial class AddProceduresConfigRulesRgl01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flit.Infrastructure.Persistence.IdentityCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CambiadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cambiado_en");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId");

                    b.ToTable("identity_credentials", "identity");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Joins.RoleMenuItemEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.HasKey("RoleId", "MenuItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("role_menu_items", "rbac");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Joins.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "rbac");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Joins.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "rbac");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.RefreshTokenEntry", b =>
                {
                    b.Property<Guid>("Jti")
                        .HasColumnType("uuid")
                        .HasColumnName("jti");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_identity_refresh_tokens_expires_at");

                    b.ToTable("identity_refresh_tokens", "identity");
                });

            modelBuilder.Entity("Flit.Modules.Identity.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<bool>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bloqueado");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EmailVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verificado");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<Guid?>("OrganismoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organismo_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTimeOffset?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_identity_users_activo");

                    b.ToTable("identity_users", "identity");
                });

            modelBuilder.Entity("Flit.Modules.Notifications.Domain.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Asunto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CuerpoResumen")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("body_excerpt");

                    b.Property<string>("DestinatarioContacto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient_masked");

                    b.Property<Guid?>("DestinatarioUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<DateTimeOffset?>("EnviadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("ErrorMensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("notification_type");

                    b.Property<Guid?>("TramiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_id");

                    b.HasKey("Id");

                    b.HasIndex("CreadoEn")
                        .HasDatabaseName("ix_notification_delivery_created_at");

                    b.HasIndex("DestinatarioUserId")
                        .HasDatabaseName("ix_notification_delivery_recipient_user_id");

                    b.HasIndex("TramiteId")
                        .HasDatabaseName("ix_notification_delivery_procedure_id");

                    b.ToTable("notification_delivery", "notifications");
                });

            modelBuilder.Entity("Flit.Modules.Rbac.Domain.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FrontendPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("frontend_path");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSeparator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_separator");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("label");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_menu_items_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_menu_items_parent");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_menu_items_sort");

                    b.ToTable("menu_items", "rbac");
                });

            modelBuilder.Entity("Flit.Modules.Rbac.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_permissions_module");

                    b.ToTable("permissions", "rbac");
                });

            modelBuilder.Entity("Flit.Modules.Rbac.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", "rbac");
                });

            modelBuilder.Entity("Flit.Modules.Users.Domain.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_prt_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_prt_user_id");

                    b.ToTable("password_reset_tokens", "identity");
                });

            modelBuilder.Entity("Flit.Modules.Users.Domain.SyncInconsistency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("CognitoSub")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cognito_sub");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_sync_type_unresolved")
                        .HasFilter("resolved_at IS NULL");

                    b.ToTable("sync_inconsistencies", "identity", t =>
                        {
                            t.HasCheckConstraint("chk_sync_type", "type IN ('COGNITO_ORPHAN','DB_ORPHAN','STATUS_DESYNCED')");
                        });
                });

            modelBuilder.Entity("Flit.Modules.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CognitoSub")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cognito_sub");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("document_type");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mfa_enabled");

                    b.Property<DateTimeOffset?>("MfaEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enabled_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CognitoSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_cognito_sub")
                        .HasFilter("cognito_sub IS NOT NULL");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("DocumentType", "DocumentNumber")
                        .HasDatabaseName("ix_users_document")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasCheckConstraint("chk_users_status", "status IN ('ACTIVE','INACTIVE','BLOCKED','DELETED')");
                        });
                });

            modelBuilder.Entity("Flit.Modules.Users.Domain.UserAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event");

                    b.Property<Guid?>("ExecutedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("executed_by_user_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Event")
                        .HasDatabaseName("ix_ual_event");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_ual_occurred_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ual_user_id");

                    b.ToTable("user_audit_log", "identity");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Joins.RoleMenuItemEntity", b =>
                {
                    b.HasOne("Flit.Modules.Rbac.Domain.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rmi_mi");

                    b.HasOne("Flit.Modules.Rbac.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rmi_role");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Joins.RolePermissionEntity", b =>
                {
                    b.HasOne("Flit.Modules.Rbac.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rp_permission");

                    b.HasOne("Flit.Modules.Rbac.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rp_role");
                });

            modelBuilder.Entity("Flit.Infrastructure.Persistence.Joins.UserRoleEntity", b =>
                {
                    b.HasOne("Flit.Modules.Rbac.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ur_role");

                    b.HasOne("Flit.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ur_user");
                });

            modelBuilder.Entity("Flit.Modules.Identity.Domain.Usuario", b =>
                {
                    b.OwnsOne("Flit.Modules.Identity.Domain.Documento", "Documento", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("documento_numero");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("documento_tipo");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Tipo", "Numero")
                                .IsUnique()
                                .HasDatabaseName("ix_identity_users_documento");

                            b1.ToTable("identity_users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Flit.Modules.Identity.Domain.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_identity_users_email");

                            b1.ToTable("identity_users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Flit.Modules.Identity.Domain.HabeasDataConsent", "Consent", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("ConsentimientoOtorgado")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("habeas_data_consentimiento");

                            b1.Property<DateTimeOffset>("FechaConsentimiento")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("habeas_data_fecha");

                            b1.Property<string>("PoliticaVersion")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("habeas_data_politica_version");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("identity_users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Consent")
                        .IsRequired();

                    b.Navigation("Documento")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("Flit.Modules.Rbac.Domain.MenuItem", b =>
                {
                    b.HasOne("Flit.Modules.Rbac.Domain.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mi_parent");
                });

            modelBuilder.Entity("Flit.Modules.Users.Domain.PasswordResetToken", b =>
                {
                    b.HasOne("Flit.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prt_user");
                });

            modelBuilder.Entity("Flit.Modules.Users.Domain.User", b =>
                {
                    b.HasOne("Flit.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_created_by");

                    b.OwnsOne("Flit.Modules.Users.Domain.MfaSecret", "MfaSecret", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("mfa_secret_ciphertext");

                            b1.Property<string>("KeyId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("mfa_secret_key_id");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("mfa_secret_nonce");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("MfaSecret");
                });

            modelBuilder.Entity("Flit.Modules.Users.Domain.UserAuditLog", b =>
                {
                    b.HasOne("Flit.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_ual_user");
                });
#pragma warning restore 612, 618
        }
    }
}
