<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Flit.Modules.Identity</RootNamespace>
    <!-- AOT incompatible: IdentityModel usa reflection, BCrypt usa reflection -->
    <PublishAot>false</PublishAot>
    <IsAotCompatible>false</IsAotCompatible>
    <NuGetAuditMode>direct</NuGetAuditMode>
    <NoWarn>$(NoWarn);CA1711</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flit.Infrastructure\Flit.Infrastructure.csproj" />
    <ProjectReference Include="..\Flit.SharedKernel\Flit.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

</Project>
